# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/armor_piece.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import fighter_move_blueprint_pb2 as proto_dot_fighter__move__blueprint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/armor_piece.proto',
  package='pxd.proto',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17proto/armor_piece.proto\x12\tpxd.proto\x1a\"proto/fighter_move_blueprint.proto\"\\\n\nArmorPiece\x12\r\n\x05\x43\x61ndy\x18\x01 \x01(\t\x12\x11\n\tArmorType\x18\x02 \x01(\r\x12\x14\n\x0cRewardSource\x18\x03 \x01(\r\x12\x16\n\x0eRewardSourceID\x18\x04 \x01(\rB\x03\xf8\x01\x01'
  ,
  dependencies=[proto_dot_fighter__move__blueprint__pb2.DESCRIPTOR,])




_ARMORPIECE = _descriptor.Descriptor(
  name='ArmorPiece',
  full_name='pxd.proto.ArmorPiece',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Candy', full_name='pxd.proto.ArmorPiece.Candy', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ArmorType', full_name='pxd.proto.ArmorPiece.ArmorType', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RewardSource', full_name='pxd.proto.ArmorPiece.RewardSource', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RewardSourceID', full_name='pxd.proto.ArmorPiece.RewardSourceID', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=166,
)

DESCRIPTOR.message_types_by_name['ArmorPiece'] = _ARMORPIECE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArmorPiece = _reflection.GeneratedProtocolMessageType('ArmorPiece', (_message.Message,), {
  'DESCRIPTOR' : _ARMORPIECE,
  '__module__' : 'proto.armor_piece_pb2'
  # @@protoc_insertion_point(class_scope:pxd.proto.ArmorPiece)
  })
_sym_db.RegisterMessage(ArmorPiece)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
