# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/config.proto',
  package='pxd.proto',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/config.proto\x12\tpxd.proto\"7\n\rBurnsaleStage\x12\x13\n\x0b\x61mount_sold\x18\x01 \x01(\x04\x12\x11\n\tprice_sat\x18\x02 \x01(\x04\"\xfe\x03\n\x06Params\x12\x16\n\x0e\x63haracter_cost\x18\x01 \x01(\x03\x12\x17\n\x0f\x63haracter_limit\x18\x02 \x01(\r\x12\x1c\n\x14\x62locked_step_retries\x18\x03 \x01(\r\x12\x1a\n\x12\x64\x61mage_list_blocks\x18\x04 \x01(\r\x12!\n\x19prospection_expiry_blocks\x18\x05 \x01(\r\x12\"\n\x1a\x61rmour_repair_hp_per_block\x18\x06 \x01(\r\x12!\n\x19\x61rmour_repair_cost_millis\x18\x07 \x01(\r\x12\x14\n\x0c\x62p_copy_cost\x18\x08 \x01(\x03\x12\x16\n\x0e\x62p_copy_blocks\x18\t \x01(\r\x12\x19\n\x11\x63onstruction_cost\x18\n \x01(\x03\x12\x1b\n\x13\x63onstruction_blocks\x18\x0b \x01(\r\x12\x1d\n\x15\x62uilding_update_delay\x18\x0c \x01(\r\x12\x13\n\x0b\x64\x65x_fee_bps\x18\r \x01(\r\x12\x16\n\x0emin_region_ore\x18\x0e \x01(\x03\x12\x16\n\x0emax_region_ore\x18\x0f \x01(\x03\x12\x10\n\x08\x64\x65v_addr\x18\x10 \x01(\t\x12\x10\n\x08god_mode\x18\x11 \x01(\x08\x12\x31\n\x0f\x62urnsale_stages\x18\x12 \x03(\x0b\x32\x18.pxd.proto.BurnsaleStage\"\x8b\x01\n\nConfigData\x12!\n\x06params\x18\x01 \x01(\x0b\x32\x11.pxd.proto.Params\x12,\n\rtestnet_merge\x18\x64 \x01(\x0b\x32\x15.pxd.proto.ConfigData\x12,\n\rregtest_merge\x18\x65 \x01(\x0b\x32\x15.pxd.proto.ConfigDataB\x03\xf8\x01\x01'
)




_BURNSALESTAGE = _descriptor.Descriptor(
  name='BurnsaleStage',
  full_name='pxd.proto.BurnsaleStage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount_sold', full_name='pxd.proto.BurnsaleStage.amount_sold', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_sat', full_name='pxd.proto.BurnsaleStage.price_sat', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=88,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='pxd.proto.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='character_cost', full_name='pxd.proto.Params.character_cost', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='character_limit', full_name='pxd.proto.Params.character_limit', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blocked_step_retries', full_name='pxd.proto.Params.blocked_step_retries', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='damage_list_blocks', full_name='pxd.proto.Params.damage_list_blocks', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prospection_expiry_blocks', full_name='pxd.proto.Params.prospection_expiry_blocks', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='armour_repair_hp_per_block', full_name='pxd.proto.Params.armour_repair_hp_per_block', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='armour_repair_cost_millis', full_name='pxd.proto.Params.armour_repair_cost_millis', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bp_copy_cost', full_name='pxd.proto.Params.bp_copy_cost', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bp_copy_blocks', full_name='pxd.proto.Params.bp_copy_blocks', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='construction_cost', full_name='pxd.proto.Params.construction_cost', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='construction_blocks', full_name='pxd.proto.Params.construction_blocks', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='building_update_delay', full_name='pxd.proto.Params.building_update_delay', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dex_fee_bps', full_name='pxd.proto.Params.dex_fee_bps', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_region_ore', full_name='pxd.proto.Params.min_region_ore', index=13,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_region_ore', full_name='pxd.proto.Params.max_region_ore', index=14,
      number=15, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dev_addr', full_name='pxd.proto.Params.dev_addr', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='god_mode', full_name='pxd.proto.Params.god_mode', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='burnsale_stages', full_name='pxd.proto.Params.burnsale_stages', index=17,
      number=18, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=601,
)


_CONFIGDATA = _descriptor.Descriptor(
  name='ConfigData',
  full_name='pxd.proto.ConfigData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='pxd.proto.ConfigData.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='testnet_merge', full_name='pxd.proto.ConfigData.testnet_merge', index=1,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regtest_merge', full_name='pxd.proto.ConfigData.regtest_merge', index=2,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=604,
  serialized_end=743,
)

_PARAMS.fields_by_name['burnsale_stages'].message_type = _BURNSALESTAGE
_CONFIGDATA.fields_by_name['params'].message_type = _PARAMS
_CONFIGDATA.fields_by_name['testnet_merge'].message_type = _CONFIGDATA
_CONFIGDATA.fields_by_name['regtest_merge'].message_type = _CONFIGDATA
DESCRIPTOR.message_types_by_name['BurnsaleStage'] = _BURNSALESTAGE
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['ConfigData'] = _CONFIGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BurnsaleStage = _reflection.GeneratedProtocolMessageType('BurnsaleStage', (_message.Message,), {
  'DESCRIPTOR' : _BURNSALESTAGE,
  '__module__' : 'proto.config_pb2'
  # @@protoc_insertion_point(class_scope:pxd.proto.BurnsaleStage)
  })
_sym_db.RegisterMessage(BurnsaleStage)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'proto.config_pb2'
  # @@protoc_insertion_point(class_scope:pxd.proto.Params)
  })
_sym_db.RegisterMessage(Params)

ConfigData = _reflection.GeneratedProtocolMessageType('ConfigData', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGDATA,
  '__module__' : 'proto.config_pb2'
  # @@protoc_insertion_point(class_scope:pxd.proto.ConfigData)
  })
_sym_db.RegisterMessage(ConfigData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
