# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/crystal_bundle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/crystal_bundle.proto',
  package='pxd.proto',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aproto/crystal_bundle.proto\x12\tpxd.proto\"F\n\rCrystalBundle\x12\x12\n\nAuthoredId\x18\x01 \x01(\t\x12\x10\n\x08Quantity\x18\x02 \x01(\r\x12\x0f\n\x07\x43HICost\x18\x03 \x01(\x02\x42\x03\xf8\x01\x01'
)




_CRYSTALBUNDLE = _descriptor.Descriptor(
  name='CrystalBundle',
  full_name='pxd.proto.CrystalBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='AuthoredId', full_name='pxd.proto.CrystalBundle.AuthoredId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Quantity', full_name='pxd.proto.CrystalBundle.Quantity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CHICost', full_name='pxd.proto.CrystalBundle.CHICost', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['CrystalBundle'] = _CRYSTALBUNDLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrystalBundle = _reflection.GeneratedProtocolMessageType('CrystalBundle', (_message.Message,), {
  'DESCRIPTOR' : _CRYSTALBUNDLE,
  '__module__' : 'proto.crystal_bundle_pb2'
  # @@protoc_insertion_point(class_scope:pxd.proto.CrystalBundle)
  })
_sym_db.RegisterMessage(CrystalBundle)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
