// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fighter_move_blueprint.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2ffighter_5fmove_5fblueprint_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2ffighter_5fmove_5fblueprint_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3016000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3016000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2ffighter_5fmove_5fblueprint_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2ffighter_5fmove_5fblueprint_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2ffighter_5fmove_5fblueprint_2eproto;
namespace pxd {
namespace proto {
class FighterMoveBlueprint;
struct FighterMoveBlueprintDefaultTypeInternal;
extern FighterMoveBlueprintDefaultTypeInternal _FighterMoveBlueprint_default_instance_;
}  // namespace proto
}  // namespace pxd
PROTOBUF_NAMESPACE_OPEN
template<> ::pxd::proto::FighterMoveBlueprint* Arena::CreateMaybeMessage<::pxd::proto::FighterMoveBlueprint>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pxd {
namespace proto {

// ===================================================================

class FighterMoveBlueprint PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pxd.proto.FighterMoveBlueprint) */ {
 public:
  inline FighterMoveBlueprint() : FighterMoveBlueprint(nullptr) {}
  ~FighterMoveBlueprint() override;
  explicit constexpr FighterMoveBlueprint(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FighterMoveBlueprint(const FighterMoveBlueprint& from);
  FighterMoveBlueprint(FighterMoveBlueprint&& from) noexcept
    : FighterMoveBlueprint() {
    *this = ::std::move(from);
  }

  inline FighterMoveBlueprint& operator=(const FighterMoveBlueprint& from) {
    CopyFrom(from);
    return *this;
  }
  inline FighterMoveBlueprint& operator=(FighterMoveBlueprint&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FighterMoveBlueprint& default_instance() {
    return *internal_default_instance();
  }
  static inline const FighterMoveBlueprint* internal_default_instance() {
    return reinterpret_cast<const FighterMoveBlueprint*>(
               &_FighterMoveBlueprint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FighterMoveBlueprint& a, FighterMoveBlueprint& b) {
    a.Swap(&b);
  }
  inline void Swap(FighterMoveBlueprint* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FighterMoveBlueprint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FighterMoveBlueprint* New() const final {
    return CreateMaybeMessage<FighterMoveBlueprint>(nullptr);
  }

  FighterMoveBlueprint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FighterMoveBlueprint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FighterMoveBlueprint& from);
  void MergeFrom(const FighterMoveBlueprint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FighterMoveBlueprint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pxd.proto.FighterMoveBlueprint";
  }
  protected:
  explicit FighterMoveBlueprint(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAuthoredIdFieldNumber = 1,
    kNameFieldNumber = 2,
    kCandyTypeFieldNumber = 3,
    kQualityFieldNumber = 4,
    kMoveTypeFieldNumber = 5,
  };
  // optional string AuthoredId = 1;
  bool has_authoredid() const;
  private:
  bool _internal_has_authoredid() const;
  public:
  void clear_authoredid();
  const std::string& authoredid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_authoredid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_authoredid();
  std::string* release_authoredid();
  void set_allocated_authoredid(std::string* authoredid);
  private:
  const std::string& _internal_authoredid() const;
  void _internal_set_authoredid(const std::string& value);
  std::string* _internal_mutable_authoredid();
  public:

  // optional string Name = 2;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional string CandyType = 3;
  bool has_candytype() const;
  private:
  bool _internal_has_candytype() const;
  public:
  void clear_candytype();
  const std::string& candytype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_candytype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_candytype();
  std::string* release_candytype();
  void set_allocated_candytype(std::string* candytype);
  private:
  const std::string& _internal_candytype() const;
  void _internal_set_candytype(const std::string& value);
  std::string* _internal_mutable_candytype();
  public:

  // optional uint32 Quality = 4;
  bool has_quality() const;
  private:
  bool _internal_has_quality() const;
  public:
  void clear_quality();
  ::PROTOBUF_NAMESPACE_ID::uint32 quality() const;
  void set_quality(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_quality() const;
  void _internal_set_quality(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 MoveType = 5;
  bool has_movetype() const;
  private:
  bool _internal_has_movetype() const;
  public:
  void clear_movetype();
  ::PROTOBUF_NAMESPACE_ID::uint32 movetype() const;
  void set_movetype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_movetype() const;
  void _internal_set_movetype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:pxd.proto.FighterMoveBlueprint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr authoredid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr candytype_;
  ::PROTOBUF_NAMESPACE_ID::uint32 quality_;
  ::PROTOBUF_NAMESPACE_ID::uint32 movetype_;
  friend struct ::TableStruct_proto_2ffighter_5fmove_5fblueprint_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FighterMoveBlueprint

// optional string AuthoredId = 1;
inline bool FighterMoveBlueprint::_internal_has_authoredid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool FighterMoveBlueprint::has_authoredid() const {
  return _internal_has_authoredid();
}
inline void FighterMoveBlueprint::clear_authoredid() {
  authoredid_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& FighterMoveBlueprint::authoredid() const {
  // @@protoc_insertion_point(field_get:pxd.proto.FighterMoveBlueprint.AuthoredId)
  return _internal_authoredid();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void FighterMoveBlueprint::set_authoredid(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 authoredid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:pxd.proto.FighterMoveBlueprint.AuthoredId)
}
inline std::string* FighterMoveBlueprint::mutable_authoredid() {
  // @@protoc_insertion_point(field_mutable:pxd.proto.FighterMoveBlueprint.AuthoredId)
  return _internal_mutable_authoredid();
}
inline const std::string& FighterMoveBlueprint::_internal_authoredid() const {
  return authoredid_.Get();
}
inline void FighterMoveBlueprint::_internal_set_authoredid(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  authoredid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* FighterMoveBlueprint::_internal_mutable_authoredid() {
  _has_bits_[0] |= 0x00000001u;
  return authoredid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FighterMoveBlueprint::release_authoredid() {
  // @@protoc_insertion_point(field_release:pxd.proto.FighterMoveBlueprint.AuthoredId)
  if (!_internal_has_authoredid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return authoredid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FighterMoveBlueprint::set_allocated_authoredid(std::string* authoredid) {
  if (authoredid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  authoredid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), authoredid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pxd.proto.FighterMoveBlueprint.AuthoredId)
}

// optional string Name = 2;
inline bool FighterMoveBlueprint::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool FighterMoveBlueprint::has_name() const {
  return _internal_has_name();
}
inline void FighterMoveBlueprint::clear_name() {
  name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& FighterMoveBlueprint::name() const {
  // @@protoc_insertion_point(field_get:pxd.proto.FighterMoveBlueprint.Name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void FighterMoveBlueprint::set_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:pxd.proto.FighterMoveBlueprint.Name)
}
inline std::string* FighterMoveBlueprint::mutable_name() {
  // @@protoc_insertion_point(field_mutable:pxd.proto.FighterMoveBlueprint.Name)
  return _internal_mutable_name();
}
inline const std::string& FighterMoveBlueprint::_internal_name() const {
  return name_.Get();
}
inline void FighterMoveBlueprint::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* FighterMoveBlueprint::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000002u;
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FighterMoveBlueprint::release_name() {
  // @@protoc_insertion_point(field_release:pxd.proto.FighterMoveBlueprint.Name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FighterMoveBlueprint::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pxd.proto.FighterMoveBlueprint.Name)
}

// optional string CandyType = 3;
inline bool FighterMoveBlueprint::_internal_has_candytype() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool FighterMoveBlueprint::has_candytype() const {
  return _internal_has_candytype();
}
inline void FighterMoveBlueprint::clear_candytype() {
  candytype_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& FighterMoveBlueprint::candytype() const {
  // @@protoc_insertion_point(field_get:pxd.proto.FighterMoveBlueprint.CandyType)
  return _internal_candytype();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void FighterMoveBlueprint::set_candytype(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 candytype_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:pxd.proto.FighterMoveBlueprint.CandyType)
}
inline std::string* FighterMoveBlueprint::mutable_candytype() {
  // @@protoc_insertion_point(field_mutable:pxd.proto.FighterMoveBlueprint.CandyType)
  return _internal_mutable_candytype();
}
inline const std::string& FighterMoveBlueprint::_internal_candytype() const {
  return candytype_.Get();
}
inline void FighterMoveBlueprint::_internal_set_candytype(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  candytype_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* FighterMoveBlueprint::_internal_mutable_candytype() {
  _has_bits_[0] |= 0x00000004u;
  return candytype_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FighterMoveBlueprint::release_candytype() {
  // @@protoc_insertion_point(field_release:pxd.proto.FighterMoveBlueprint.CandyType)
  if (!_internal_has_candytype()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return candytype_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FighterMoveBlueprint::set_allocated_candytype(std::string* candytype) {
  if (candytype != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  candytype_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), candytype,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pxd.proto.FighterMoveBlueprint.CandyType)
}

// optional uint32 Quality = 4;
inline bool FighterMoveBlueprint::_internal_has_quality() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool FighterMoveBlueprint::has_quality() const {
  return _internal_has_quality();
}
inline void FighterMoveBlueprint::clear_quality() {
  quality_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FighterMoveBlueprint::_internal_quality() const {
  return quality_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FighterMoveBlueprint::quality() const {
  // @@protoc_insertion_point(field_get:pxd.proto.FighterMoveBlueprint.Quality)
  return _internal_quality();
}
inline void FighterMoveBlueprint::_internal_set_quality(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  quality_ = value;
}
inline void FighterMoveBlueprint::set_quality(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_quality(value);
  // @@protoc_insertion_point(field_set:pxd.proto.FighterMoveBlueprint.Quality)
}

// optional uint32 MoveType = 5;
inline bool FighterMoveBlueprint::_internal_has_movetype() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool FighterMoveBlueprint::has_movetype() const {
  return _internal_has_movetype();
}
inline void FighterMoveBlueprint::clear_movetype() {
  movetype_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FighterMoveBlueprint::_internal_movetype() const {
  return movetype_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FighterMoveBlueprint::movetype() const {
  // @@protoc_insertion_point(field_get:pxd.proto.FighterMoveBlueprint.MoveType)
  return _internal_movetype();
}
inline void FighterMoveBlueprint::_internal_set_movetype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  movetype_ = value;
}
inline void FighterMoveBlueprint::set_movetype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_movetype(value);
  // @@protoc_insertion_point(field_set:pxd.proto.FighterMoveBlueprint.MoveType)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace pxd

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2ffighter_5fmove_5fblueprint_2eproto
