# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/inventory.proto',
  package='pxd.proto',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/inventory.proto\x12\tpxd.proto\"r\n\tInventory\x12\x34\n\x08\x66ungible\x18\x01 \x03(\x0b\x32\".pxd.proto.Inventory.FungibleEntry\x1a/\n\rFungibleEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x42\x03\xf8\x01\x01'
)




_INVENTORY_FUNGIBLEENTRY = _descriptor.Descriptor(
  name='FungibleEntry',
  full_name='pxd.proto.Inventory.FungibleEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pxd.proto.Inventory.FungibleEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='pxd.proto.Inventory.FungibleEntry.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=150,
)

_INVENTORY = _descriptor.Descriptor(
  name='Inventory',
  full_name='pxd.proto.Inventory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fungible', full_name='pxd.proto.Inventory.fungible', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INVENTORY_FUNGIBLEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=150,
)

_INVENTORY_FUNGIBLEENTRY.containing_type = _INVENTORY
_INVENTORY.fields_by_name['fungible'].message_type = _INVENTORY_FUNGIBLEENTRY
DESCRIPTOR.message_types_by_name['Inventory'] = _INVENTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Inventory = _reflection.GeneratedProtocolMessageType('Inventory', (_message.Message,), {

  'FungibleEntry' : _reflection.GeneratedProtocolMessageType('FungibleEntry', (_message.Message,), {
    'DESCRIPTOR' : _INVENTORY_FUNGIBLEENTRY,
    '__module__' : 'proto.inventory_pb2'
    # @@protoc_insertion_point(class_scope:pxd.proto.Inventory.FungibleEntry)
    })
  ,
  'DESCRIPTOR' : _INVENTORY,
  '__module__' : 'proto.inventory_pb2'
  # @@protoc_insertion_point(class_scope:pxd.proto.Inventory)
  })
_sym_db.RegisterMessage(Inventory)
_sym_db.RegisterMessage(Inventory.FungibleEntry)


DESCRIPTOR._options = None
_INVENTORY_FUNGIBLEENTRY._options = None
# @@protoc_insertion_point(module_scope)
