// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ongoing.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fongoing_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fongoing_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3016000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3016000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fongoing_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fongoing_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fongoing_2eproto;
namespace pxd {
namespace proto {
class OngoinOperation;
struct OngoinOperationDefaultTypeInternal;
extern OngoinOperationDefaultTypeInternal _OngoinOperation_default_instance_;
}  // namespace proto
}  // namespace pxd
PROTOBUF_NAMESPACE_OPEN
template<> ::pxd::proto::OngoinOperation* Arena::CreateMaybeMessage<::pxd::proto::OngoinOperation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pxd {
namespace proto {

// ===================================================================

class OngoinOperation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pxd.proto.OngoinOperation) */ {
 public:
  inline OngoinOperation() : OngoinOperation(nullptr) {}
  ~OngoinOperation() override;
  explicit constexpr OngoinOperation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OngoinOperation(const OngoinOperation& from);
  OngoinOperation(OngoinOperation&& from) noexcept
    : OngoinOperation() {
    *this = ::std::move(from);
  }

  inline OngoinOperation& operator=(const OngoinOperation& from) {
    CopyFrom(from);
    return *this;
  }
  inline OngoinOperation& operator=(OngoinOperation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OngoinOperation& default_instance() {
    return *internal_default_instance();
  }
  static inline const OngoinOperation* internal_default_instance() {
    return reinterpret_cast<const OngoinOperation*>(
               &_OngoinOperation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OngoinOperation& a, OngoinOperation& b) {
    a.Swap(&b);
  }
  inline void Swap(OngoinOperation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OngoinOperation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OngoinOperation* New() const final {
    return CreateMaybeMessage<OngoinOperation>(nullptr);
  }

  OngoinOperation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OngoinOperation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OngoinOperation& from);
  void MergeFrom(const OngoinOperation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OngoinOperation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pxd.proto.OngoinOperation";
  }
  protected:
  explicit OngoinOperation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemAuthIDFieldNumber = 3,
    kBlocksLeftFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // optional string ItemAuthID = 3;
  bool has_itemauthid() const;
  private:
  bool _internal_has_itemauthid() const;
  public:
  void clear_itemauthid();
  const std::string& itemauthid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_itemauthid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_itemauthid();
  std::string* release_itemauthid();
  void set_allocated_itemauthid(std::string* itemauthid);
  private:
  const std::string& _internal_itemauthid() const;
  void _internal_set_itemauthid(const std::string& value);
  std::string* _internal_mutable_itemauthid();
  public:

  // optional uint32 BlocksLeft = 1;
  bool has_blocksleft() const;
  private:
  bool _internal_has_blocksleft() const;
  public:
  void clear_blocksleft();
  ::PROTOBUF_NAMESPACE_ID::uint32 blocksleft() const;
  void set_blocksleft(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_blocksleft() const;
  void _internal_set_blocksleft(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 Type = 2;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_type() const;
  void _internal_set_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:pxd.proto.OngoinOperation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr itemauthid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 blocksleft_;
  ::PROTOBUF_NAMESPACE_ID::uint32 type_;
  friend struct ::TableStruct_proto_2fongoing_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OngoinOperation

// optional uint32 BlocksLeft = 1;
inline bool OngoinOperation::_internal_has_blocksleft() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool OngoinOperation::has_blocksleft() const {
  return _internal_has_blocksleft();
}
inline void OngoinOperation::clear_blocksleft() {
  blocksleft_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OngoinOperation::_internal_blocksleft() const {
  return blocksleft_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OngoinOperation::blocksleft() const {
  // @@protoc_insertion_point(field_get:pxd.proto.OngoinOperation.BlocksLeft)
  return _internal_blocksleft();
}
inline void OngoinOperation::_internal_set_blocksleft(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  blocksleft_ = value;
}
inline void OngoinOperation::set_blocksleft(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_blocksleft(value);
  // @@protoc_insertion_point(field_set:pxd.proto.OngoinOperation.BlocksLeft)
}

// optional uint32 Type = 2;
inline bool OngoinOperation::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool OngoinOperation::has_type() const {
  return _internal_has_type();
}
inline void OngoinOperation::clear_type() {
  type_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OngoinOperation::_internal_type() const {
  return type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OngoinOperation::type() const {
  // @@protoc_insertion_point(field_get:pxd.proto.OngoinOperation.Type)
  return _internal_type();
}
inline void OngoinOperation::_internal_set_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  type_ = value;
}
inline void OngoinOperation::set_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:pxd.proto.OngoinOperation.Type)
}

// optional string ItemAuthID = 3;
inline bool OngoinOperation::_internal_has_itemauthid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool OngoinOperation::has_itemauthid() const {
  return _internal_has_itemauthid();
}
inline void OngoinOperation::clear_itemauthid() {
  itemauthid_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& OngoinOperation::itemauthid() const {
  // @@protoc_insertion_point(field_get:pxd.proto.OngoinOperation.ItemAuthID)
  return _internal_itemauthid();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void OngoinOperation::set_itemauthid(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 itemauthid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:pxd.proto.OngoinOperation.ItemAuthID)
}
inline std::string* OngoinOperation::mutable_itemauthid() {
  // @@protoc_insertion_point(field_mutable:pxd.proto.OngoinOperation.ItemAuthID)
  return _internal_mutable_itemauthid();
}
inline const std::string& OngoinOperation::_internal_itemauthid() const {
  return itemauthid_.Get();
}
inline void OngoinOperation::_internal_set_itemauthid(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  itemauthid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* OngoinOperation::_internal_mutable_itemauthid() {
  _has_bits_[0] |= 0x00000001u;
  return itemauthid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* OngoinOperation::release_itemauthid() {
  // @@protoc_insertion_point(field_release:pxd.proto.OngoinOperation.ItemAuthID)
  if (!_internal_has_itemauthid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return itemauthid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OngoinOperation::set_allocated_itemauthid(std::string* itemauthid) {
  if (itemauthid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  itemauthid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), itemauthid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pxd.proto.OngoinOperation.ItemAuthID)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace pxd

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fongoing_2eproto
