# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ongoing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ongoing.proto',
  package='pxd.proto',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13proto/ongoing.proto\x12\tpxd.proto\"G\n\x0fOngoinOperation\x12\x12\n\nBlocksLeft\x18\x01 \x01(\r\x12\x0c\n\x04Type\x18\x02 \x01(\r\x12\x12\n\nItemAuthID\x18\x03 \x01(\tB\x03\xf8\x01\x01'
)




_ONGOINOPERATION = _descriptor.Descriptor(
  name='OngoinOperation',
  full_name='pxd.proto.OngoinOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='BlocksLeft', full_name='pxd.proto.OngoinOperation.BlocksLeft', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Type', full_name='pxd.proto.OngoinOperation.Type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ItemAuthID', full_name='pxd.proto.OngoinOperation.ItemAuthID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['OngoinOperation'] = _ONGOINOPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OngoinOperation = _reflection.GeneratedProtocolMessageType('OngoinOperation', (_message.Message,), {
  'DESCRIPTOR' : _ONGOINOPERATION,
  '__module__' : 'proto.ongoing_pb2'
  # @@protoc_insertion_point(class_scope:pxd.proto.OngoinOperation)
  })
_sym_db.RegisterMessage(OngoinOperation)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
