# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tournament_blueprint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/tournament_blueprint.proto',
  package='pxd.proto',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n proto/tournament_blueprint.proto\x12\tpxd.proto\"\xb0\x02\n\x13TournamentBlueprint\x12\x12\n\nAuthoredId\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x10\n\x08\x44uration\x18\x03 \x01(\r\x12\x11\n\tTeamCount\x18\x04 \x01(\r\x12\x10\n\x08TeamSize\x18\x05 \x01(\r\x12\x14\n\x0cMinSweetness\x18\x06 \x01(\r\x12\x14\n\x0cMaxSweetness\x18\x07 \x01(\r\x12\x18\n\x10MaxRewardQuality\x18\x08 \x01(\r\x12\x1a\n\x12\x42\x61seRewardsTableId\x18\t \x01(\t\x12\x15\n\rBaseRollCount\x18\n \x01(\r\x12\x1c\n\x14WinnerRewardsTableId\x18\x0b \x01(\t\x12\x17\n\x0fWinnerRollCount\x18\x0c \x01(\r\x12\x10\n\x08JoinCost\x18\r \x01(\rB\x03\xf8\x01\x01'
)




_TOURNAMENTBLUEPRINT = _descriptor.Descriptor(
  name='TournamentBlueprint',
  full_name='pxd.proto.TournamentBlueprint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='AuthoredId', full_name='pxd.proto.TournamentBlueprint.AuthoredId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='pxd.proto.TournamentBlueprint.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='pxd.proto.TournamentBlueprint.Duration', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TeamCount', full_name='pxd.proto.TournamentBlueprint.TeamCount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TeamSize', full_name='pxd.proto.TournamentBlueprint.TeamSize', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MinSweetness', full_name='pxd.proto.TournamentBlueprint.MinSweetness', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MaxSweetness', full_name='pxd.proto.TournamentBlueprint.MaxSweetness', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MaxRewardQuality', full_name='pxd.proto.TournamentBlueprint.MaxRewardQuality', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BaseRewardsTableId', full_name='pxd.proto.TournamentBlueprint.BaseRewardsTableId', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BaseRollCount', full_name='pxd.proto.TournamentBlueprint.BaseRollCount', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='WinnerRewardsTableId', full_name='pxd.proto.TournamentBlueprint.WinnerRewardsTableId', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='WinnerRollCount', full_name='pxd.proto.TournamentBlueprint.WinnerRollCount', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='JoinCost', full_name='pxd.proto.TournamentBlueprint.JoinCost', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=352,
)

DESCRIPTOR.message_types_by_name['TournamentBlueprint'] = _TOURNAMENTBLUEPRINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TournamentBlueprint = _reflection.GeneratedProtocolMessageType('TournamentBlueprint', (_message.Message,), {
  'DESCRIPTOR' : _TOURNAMENTBLUEPRINT,
  '__module__' : 'proto.tournament_blueprint_pb2'
  # @@protoc_insertion_point(class_scope:pxd.proto.TournamentBlueprint)
  })
_sym_db.RegisterMessage(TournamentBlueprint)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
