// duel/test/moves_meta_gen.h — GENERATED by duel/gen-stats.mjs — do not edit.
//
// TEST-BINARY ONLY (see gen-stats.mjs step 4c): the move NAME and QUALITY per dense index,
// which the engine itself never needs (it resolves on power/speed/cooldown/type/effect
// alone) and which must therefore stay out of stats_gen.h and the wasm blob. The
// `--balance-report` dev tool in test_main.cpp is the only consumer.

#pragma once

#include <cstdint>

namespace duel {

struct DuelMoveMeta {
  const char* name;
  uint8_t quality; // 1..4 -- from the blueprint, never from duel-stats.json
};

constexpr DuelMoveMeta kDuelMoveMeta[39] = {
    {"Gum Drop Kick", 1}, // [0]
    {"Gilded Bonds", 4}, // [1]
    {"Quicksilver Slice", 4}, // [2]
    {"Coco Chaos", 1}, // [3]
    {"Icing on the Cake", 1}, // [4]
    {"Toffee Tripper", 3}, // [5]
    {"Pucker Sucker", 1}, // [6]
    {"Get Over Here!", 1}, // [7]
    {"Berry Bounce", 3}, // [8]
    {"Gilded Tripper", 4}, // [9]
    {"Super Sugary Rush", 4}, // [10]
    {"Candied Shell", 3}, // [11]
    {"Chewy Absorption", 2}, // [12]
    {"Tarnising Knee Drop", 4}, // [13]
    {"Heavy Gumdrop Kick", 4}, // [14]
    {"Limon Shuriken", 3}, // [15]
    {"Explosive Jawbreaker", 4}, // [16]
    {"One Thousand Tiny Slices", 1}, // [17]
    {"Sugar Shield", 1}, // [18]
    {"Candied Knuckles", 1}, // [19]
    {"Chilling Blow", 2}, // [20]
    {"Bouncing Barrage", 4}, // [21]
    {"Golden Shower of Chips", 4}, // [22]
    {"Choco Crunch", 2}, // [23]
    {"Pop Rock Pop", 1}, // [24]
    {"Bubble Trouble", 1}, // [25]
    {"Vicious Jawbreaker", 3}, // [26]
    {"Sugar Rush", 3}, // [27]
    {"Come Over Here and Slip on it", 2}, // [28]
    {"Kick in the Beans", 2}, // [29]
    {"Barfing Blow", 4}, // [30]
    {"Conductive Coat", 4}, // [31]
    {"Sugary Sweep", 1}, // [32]
    {"Right on the Button", 1}, // [33]
    {"Gold Rush", 4}, // [34]
    {"Blackout Shot", 3}, // [35]
    {"Cinnamon Blast", 2}, // [36]
    {"Silver Knuckles", 4}, // [37]
    {"Float Like a Butter Cream", 2}, // [38]
};

} // namespace duel
